version: "3.7"

services: 
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust

  api:
    build:
      context: .
      target: development
    depends_on: 
      - postgres
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment: 
      PORT: 8000
    ports:
      - "8000:8000"
    command: npm start

volumes:
  node_modules: